version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: biblioteca-db
    restart: always
    environment:
      POSTGRES_DB: biblioteca
      POSTGRES_USER: user
      POSTGRES_PASSWORD: senha123
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
